### PR TITLE
Lower php version requirements

### PR DESCRIPTION
**Pull request by philip**
This lowers the required PHP version from 5.6+ to 5.4+, although 5.3 might also work fine (depending, I've not evaluated the other parts of mysql.php).

### CODE REVIEW

**Comment by dshafik** [comment]
@philip can you update the .travis.yml to test on 5.3+?

**Comment by staabm** [comment]
Why do you need that in 5.4...? Just load the mysql-ext instead?

**Comment by dshafik** [comment]
@staabm currently if you include it, rather than being benign and doing nothing, it will cause a parse error.

**Comment by philip** [comment]
@dshafik done.
@staabm A couple reasons come to mind: not everyone controls the extensions available in their environments, and to make including this library harmless for 5.3+ users.

**Comment by staabm** [comment]
I dont like the idea of supporting people which used dead php-versions.. they should upgrade, as this missing mysql* funcs are the least problem they have.

**Comment by philip** [comment]
@dshafik Not sure how to handle this situation, but seems require-dev requires a higher PHP version due to the dependencies within. Sorry for all this extra noise I've caused :)

**Comment by dshafik** [comment]
I have fixed the tests in a different branch to work on 5.3+, the code itself is fine. Going to merge this and then apply my changes on top.

**Comment by philip** [comment]
Excellent, thanks @dshafik

**Comment by bbrala** [comment]
Oh wow, yay! You ended up fixing 5.3 support, nice.

**Pull request merged**
