### PR TITLE
Mysql defaults

### PR DESCRIPTION
**Pull request by gimler**
this replace #1 added some unit tests

### CODE REVIEW

**Comment by dshafik** [comment]
My only issue here is that `ini_get()` returns an empty string, rather than `null` if the value is not set.

You can solve this by doing:

``` php
$hostname = ini_get("mysqli.default_host") ?: null;
```

**Comment by gimler** [comment]
done

**Comment by gimler** [comment]
rebased ready for merge

**Comment by dshafik** [comment]
@gimler thanks for this! Good job! :+1:

**Pull request merged**
