### PR TITLE
Support database names with hyphens

### PR DESCRIPTION
**Pull request by stefket**

### CODE REVIEW

**Comment by staabm** [comment]
you need a similar change in a lot more places, e.g. `mysql_list_tables()`, `mysql_list_fields()`,..

**Comment by stefket** [comment]
@staabm You're right. I've just fixed these two functions, but I cannot find any other function to fix.

**Comment by staabm** [comment]
Unit tests would be great

**Comment by dshafik** [comment]
Fantastic! Great catch, and thank you for the contribution! :)

**Pull request merged**
