### PR TITLE
added default values from php.ini file if none provided

### PR DESCRIPTION
**Pull request by eryx12o45**
Hi,

thanks for this nice wrapper, as I do not call those functions with user and password all the time (because I've stored my defaults here in the php.ini file) I would need to have those defaults applied if nothing else is provided when calling a connect.

### CODE REVIEW

**Comment by dshafik** [comment]
@eryx12o45 thanks for this, I see no issue with this except to ask if there are other INI settings That can be supported? Also, if the mysqli INI settings exist, shouldn't ext/mysqli just use them like ext/mysql did? I never use these, so I haven't looked into it.

If you can, please add a sentence about needing to use the mysqli INI settings (without ext/mysql the old ones will not be available) to the README caveats section.

Thanks!

**Comment by eryx12o45** [comment]
Hi I've updated the README.md file. I hope this is fine with you.

I thought so too but unfortunately the mysqli fallback is not working for me :-( There are some more mysqli settings but actually none which are used in those functions directly. So those three should be sufficent.

Thanks!

**Comment by gimler** [comment]
:+1:

**Comment by dshafik** [comment]
Can you write some tests for this? If not, I'll try to make some time to do it shortly, I just want to make sure that this does what it should.

**Comment by gabel** [comment]
:+1:  How should a test for this config fallback look like? _Using `ini_set` and check the config values?

**Comment by dshafik** [comment]
@gabel I was thinking that you could try setting the settings with `ini_set()` and see if a connection is successful. You'll want to set any potentially conflicting settings to garbage to make sure if they are used that it fails.

**Comment by eryx12o45** [comment]
Sorry, but not sure how to do this here :-(

**Pull request closed without merging**
