### PR TITLE
Fixes so this won't break things on 5.3

### PR DESCRIPTION
**Pull request by bbrala**
Just a few small adjustments so it will at least not break older PHP versions should it be included. Currently migrating a large amount of sites which would use this shim for some of them. I would include it centrally, but then it shouldn't break older PHP versions.

### CODE REVIEW

**Comment by staabm** [comment]
@dshafik the composer.json should define the min php version in https://github.com/dshafik/php7-mysql-shim/blob/master/composer.json#L13

then we can decide whether this PR is appropriate or we dont support 5.3 at all.

per https://github.com/dshafik/php7-mysql-shim#usage I guess the min version is 5.6?

**Comment by bbrala** [comment]
I wouldn't explicitly support 5.3 i think, since the unit tests won't run on 5.3. But i feel there is no real need to use the newer language features if you can do the same without in this instance.

**Comment by staabm** [comment]
we should either support 5.3 or make use of the features which the baseline phpversion provides IMO

**Comment by dshafik** [comment]
As per #19, minimum version is intended to be 5.6. You can conditionally include this based on `PHP_VERSION` or similar if you like.

**Pull request closed without merging**
